#PATbasePATH="/pnfs/desy.de/cms/tier2/"
#TTreeBasePATH="/pnfs/desy.de/cms/tier2/"
#ROOTPrefix="root://xrootd.ba.infn.it/"
ROOTPrefix="root://cms-xrd-global.cern.ch/"
TTreeBasePATH="/pnfs/desy.de/cms/tier2/"
PATbasePATH="/pnfs/desy.de/cms/tier2/"
